"""Generate and maintain Codex permission profiles and execution rules."""

from __future__ import annotations

import json
import os
import shlex
import stat
import tempfile
from pathlib import Path, PurePosixPath
from typing import Any

import tomlkit
from tomlkit.items import Table

from twsrt.lib.models import Action, AppConfig, DiffResult, Scope, SecurityRule

_PROFILE_NAME = "twsrt"
SILENT_DEACTIVATION_WARNING = (
    "A legacy sandbox_mode setting or --sandbox flag in any other Codex "
    "config layer silently disables the twsrt permission profile; twsrt "
    "verifies only the managed config.toml. Run `codex doctor` after "
    "changing other layers."
)
_OWNED_TOP_LEVEL = {
    "default_permissions": _PROFILE_NAME,
    "approval_policy": "on-request",
    "approvals_reviewer": "user",
    "allow_login_shell": False,
}


class CodexGenerator:
    """Translate canonical twsrt intent into Codex user configuration."""

    @property
    def name(self) -> str:
        return "codex"

    def generate(self, rules: list[SecurityRule], config: AppConfig) -> str:
        """Render a secret-safe preview of the managed Codex artifacts."""
        config_text = self.generate_config(rules, config)
        preview = (
            f"--- config: {config.codex_config_path} (managed fragment) ---\n"
            f"{config_text.rstrip()}"
        )
        if config.codex_rules_path is not None:
            rules_text = self.generate_rules(rules, config)
            preview += (
                f"\n--- rules: {config.codex_rules_path} ---\n{rules_text.rstrip()}"
            )
        return preview

    def generate_config(self, rules: list[SecurityRule], config: AppConfig) -> str:
        """Render the owned Codex TOML fragment."""
        if config.srt_sandbox_enabled is False:
            raise ValueError(
                "Canonical SRT sandbox is disabled; refusing to generate a Codex "
                "full-access equivalent"
            )

        workspace_rules: dict[str, str] = {}
        additional_workspace_roots: dict[str, bool] = {}
        direct_rules: dict[str, str] = {}
        domains: dict[str, str] = {}

        for rule in rules:
            if rule.scope in (Scope.READ, Scope.WRITE):
                if rule.scope == Scope.WRITE and rule.action == Action.ALLOW:
                    workspace_root = _allow_write_workspace_root(rule.pattern)
                    if workspace_root is not None:
                        additional_workspace_roots[workspace_root] = True
                    continue
                pattern, relative = _classify_path(rule.pattern)
                access = _filesystem_access(rule, pattern)
                target = workspace_rules if relative else direct_rules
                if target.get(pattern) != "deny":
                    target[pattern] = access
            elif rule.scope == Scope.NETWORK:
                access = "deny" if rule.action == Action.DENY else "allow"
                if domains.get(rule.pattern) != "deny":
                    domains[rule.pattern] = access

        for root in _conflicting_workspace_roots(rules):
            additional_workspace_roots.pop(root, None)

        filesystem: dict[str, Any] = dict(direct_rules)
        if workspace_rules:
            filesystem[":workspace_roots"] = workspace_rules

        # domains always emitted: an empty map blocks all domain traffic,
        # matching SRT allowlist intent; omitting it would inherit :workspace
        # network defaults.
        network: dict[str, Any] = {
            "enabled": True,
            "domains": domains,
        }

        sockets = _valid_unix_socket_paths(config)
        if sockets:
            network["unix_sockets"] = {path: "allow" for path in sockets}
        if config.network_config.get("allowAllUnixSockets") is True:
            network["dangerously_allow_all_unix_sockets"] = True

        profile: dict[str, Any] = {
            "extends": ":workspace",
            "description": (
                "Generated by twsrt; edit canonical twsrt sources instead."
            ),
        }
        if additional_workspace_roots:
            profile["workspace_roots"] = additional_workspace_roots
        if filesystem:
            profile["filesystem"] = filesystem
        profile["network"] = network

        output: dict[str, Any] = dict(_OWNED_TOP_LEVEL)
        output["permissions"] = {_PROFILE_NAME: profile}
        return tomlkit.dumps(output)

    def generate_rules(self, rules: list[SecurityRule], config: AppConfig) -> str:
        """Render Codex Starlark execution rules (deny intent only).

        Only deny rules become "forbidden". Ask intent is Codex's default
        (every out-of-sandbox request prompts); allow intent would auto-approve
        unsandboxed execution and is deliberately never emitted. Output is
        therefore identical in yolo and full mode.
        """
        blocks = [
            "# Generated by twsrt; edit bash-rules.json instead.",
            "# These rules govern requests to run outside the sandbox only.",
        ]
        for rule in rules:
            if rule.scope != Scope.EXECUTE or rule.action != Action.DENY:
                continue
            try:
                pattern = shlex.split(rule.pattern)
            except ValueError as error:
                raise ValueError(
                    f"Invalid Bash rule {rule.pattern!r}: {error}"
                ) from error
            if not pattern:
                raise ValueError(f"Invalid Bash rule {rule.pattern!r}: empty command")

            pattern_text = ", ".join(json.dumps(part) for part in pattern)
            blocks.append(
                "\n".join(
                    [
                        "prefix_rule(",
                        f"    pattern = [{pattern_text}],",
                        '    decision = "forbidden",',
                        "    justification = "
                        + json.dumps("Generated from twsrt Bash intent.")
                        + ",",
                        f"    match = [{json.dumps(rule.pattern)}],",
                        ")",
                    ]
                )
            )
        return "\n\n".join(blocks) + "\n"

    def compatibility_warnings(
        self,
        config: AppConfig,
        rules: list[SecurityRule] | None = None,
    ) -> list[str]:
        """Describe canonical SRT fields that cannot be mapped without widening."""
        warnings: list[str] = []
        for raw_path in config.network_config.get("allowUnixSockets", []):
            expanded = Path(raw_path).expanduser()
            if not expanded.is_absolute() or expanded.is_dir():
                warnings.append(
                    f"Codex requires an exact absolute Unix socket path; skipped {raw_path}"
                )
        if config.network_config.get("allowLocalBinding") is True:
            warnings.append(
                "SRT allowLocalBinding is bind-only, while Codex disables its broader "
                "local/private-network guard; skipped allowLocalBinding"
            )
        for key in ("httpProxyPort", "socksProxyPort"):
            if key in config.network_config:
                warnings.append(f"Codex has no equivalent integer {key}; skipped {key}")
        ignored_sandbox_keys = sorted(
            key for key in config.sandbox_config if key != "enabled"
        )
        if ignored_sandbox_keys:
            warnings.append(
                "Codex has no equivalent for SRT sandbox fields: "
                + ", ".join(ignored_sandbox_keys)
            )
        deny_write_glob_count = sum(
            1
            for rule in rules or []
            if rule.scope == Scope.WRITE
            and rule.action == Action.DENY
            and _has_glob(rule.pattern)
        )
        if deny_write_glob_count:
            warnings.append(
                f"Codex cannot make {deny_write_glob_count} denyWrite globs "
                "read-only; compiled them as deny read and write"
            )
        unsupported_allow_write = sorted(
            rule.pattern
            for rule in rules or []
            if rule.scope == Scope.WRITE
            and rule.action == Action.ALLOW
            and not _classify_path(rule.pattern)[1]
            and _allow_write_workspace_root(rule.pattern) is None
        )
        if unsupported_allow_write:
            warnings.append(
                "Codex workspace roots must be concrete directories; skipped "
                f"{len(unsupported_allow_write)} allowWrite pattern(s): "
                + ", ".join(unsupported_allow_write)
            )
        conflicting_roots = _conflicting_workspace_roots(rules or [])
        if conflicting_roots:
            warnings.append(
                f"SRT deny rules already cover {len(conflicting_roots)} "
                "allowWrite path(s); kept the deny and skipped workspace "
                "root(s): " + ", ".join(conflicting_roots)
            )
        allow_commands = sorted(
            rule.pattern
            for rule in rules or []
            if rule.scope == Scope.EXECUTE and rule.action == Action.ALLOW
        )
        if allow_commands:
            warnings.append(
                "Codex would auto-approve unsandboxed execution for bash-rules "
                f"allow entries; skipped {len(allow_commands)} allow "
                f"rule(s): {', '.join(allow_commands)}"
            )
        ask_count = sum(
            1
            for rule in rules or []
            if rule.scope == Scope.EXECUTE and rule.action == Action.ASK
        )
        if ask_count:
            warnings.append(
                "Codex prompts for out-of-sandbox execution by default; "
                f"skipped {ask_count} ask rule(s) (no output needed)"
            )
        warnings.append(SILENT_DEACTIVATION_WARNING)
        return warnings

    def write(self, rules: list[SecurityRule], config: AppConfig) -> None:
        """Atomically merge owned config and replace the owned rules file."""
        for path, content in self.render_write_files(rules, config).items():
            _atomic_write(path, content)

    def render_write_files(
        self, rules: list[SecurityRule], config: AppConfig
    ) -> dict[Path, str]:
        """Render every owned file without mutating the filesystem."""
        generated = tomlkit.parse(self.generate_config(rules, config))
        generated_permissions = generated["permissions"]
        assert isinstance(generated_permissions, Table)
        target = config.codex_config_path
        if target.exists():
            existing = tomlkit.parse(target.read_text())
        else:
            existing = tomlkit.document()

        _reject_legacy_sandbox(existing)
        for key, value in _OWNED_TOP_LEVEL.items():
            existing[key] = value

        permissions = existing.get("permissions")
        if permissions is None:
            permissions = tomlkit.table()
            existing["permissions"] = permissions
        permissions[_PROFILE_NAME] = tomlkit.item(
            generated_permissions[_PROFILE_NAME].unwrap()
        )

        files = {target: tomlkit.dumps(existing)}
        if config.codex_rules_path is not None:
            files[config.codex_rules_path] = self.generate_rules(rules, config)
        return files

    def diff(
        self, rules: list[SecurityRule], target: Path, config: AppConfig
    ) -> DiffResult:
        """Compare only twsrt-owned Codex settings and the owned rules file."""
        generated = tomlkit.parse(self.generate_config(rules, config))
        generated_permissions = generated["permissions"]
        assert isinstance(generated_permissions, Table)
        existing = tomlkit.parse(target.read_text()) if target.exists() else {}
        _reject_legacy_sandbox(existing)

        missing: list[str] = []
        extra: list[str] = []
        for key, expected in _OWNED_TOP_LEVEL.items():
            actual = existing.get(key)
            if actual != expected:
                missing.append(f"config:{key}")
                if actual is not None:
                    extra.append(f"config:{key}")

        expected_profile = generated_permissions[_PROFILE_NAME].unwrap()
        permissions = existing.get("permissions", {})
        actual_profile = permissions.get(_PROFILE_NAME)
        actual_unwrapped = (
            actual_profile.unwrap()
            if hasattr(actual_profile, "unwrap")
            else actual_profile
        )
        if actual_unwrapped != expected_profile:
            missing.append(f"config:permissions.{_PROFILE_NAME}")
            if actual_profile is not None:
                extra.append(f"config:permissions.{_PROFILE_NAME}")

        if config.codex_rules_path is not None:
            expected_rules = self.generate_rules(rules, config)
            if not config.codex_rules_path.exists():
                missing.append(f"rules:{config.codex_rules_path}")
            elif config.codex_rules_path.read_text() != expected_rules:
                missing.append(f"rules:{config.codex_rules_path}")
                extra.append(f"rules:{config.codex_rules_path}")

        return DiffResult(
            agent=self.name,
            missing=sorted(missing),
            extra=sorted(extra),
            matched=not missing and not extra,
        )


def _filesystem_access(rule: SecurityRule, pattern: str) -> str:
    if rule.scope == Scope.READ and rule.action == Action.DENY:
        return "deny"
    if rule.scope == Scope.WRITE and rule.action == Action.DENY:
        if _has_glob(pattern):
            return "deny"
        return "read"
    raise ValueError(f"Unsupported filesystem rule: {rule}")


def _has_glob(pattern: str) -> bool:
    return any(character in pattern for character in "*?[")


def _classify_path(pattern: str) -> tuple[str, bool]:
    if pattern.startswith("/~/"):
        raise ValueError(
            f"Invalid path {pattern!r}: /~/ is a literal root directory; use ~/"
        )
    if pattern.startswith("/") or pattern.startswith("~"):
        return pattern, False

    normalized = pattern
    while normalized.startswith("./"):
        normalized = normalized[2:]
    normalized = normalized or "."
    if ".." in PurePosixPath(normalized).parts:
        raise ValueError(f"Invalid workspace-relative path {pattern!r}: contains '..'")
    return normalized, True


def _allow_write_workspace_root(pattern: str) -> str | None:
    """Return the profile workspace root for an allowWrite pattern.

    None means no root is emitted: relative paths are already writable via
    the runtime workspace; unsupported shapes (globs, ~, /) are skipped and
    reported by compatibility_warnings.
    """
    normalized, relative = _classify_path(pattern)
    if relative:
        return None

    if normalized.endswith("/**"):
        normalized = normalized.removesuffix("/**")
    normalized = normalized.rstrip("/") or "/"
    if normalized in ("~", "/") or _has_glob(normalized):
        return None
    return normalized


def _conflicting_workspace_roots(rules: list[SecurityRule]) -> list[str]:
    """Workspace roots exactly matched by a deny rule; the deny must win."""
    roots: set[str] = set()
    denied: set[str] = set()
    for rule in rules:
        if rule.scope not in (Scope.READ, Scope.WRITE):
            continue
        if rule.scope == Scope.WRITE and rule.action == Action.ALLOW:
            root = _allow_write_workspace_root(rule.pattern)
            if root is not None:
                roots.add(root)
        elif rule.action == Action.DENY:
            pattern, relative = _classify_path(rule.pattern)
            if not relative:
                denied.add(pattern)
    return sorted(roots & denied)


def _valid_unix_socket_paths(config: AppConfig) -> list[str]:
    paths: list[str] = []
    for raw_path in config.network_config.get("allowUnixSockets", []):
        expanded = Path(raw_path).expanduser()
        if not expanded.is_absolute() or expanded.is_dir():
            continue
        paths.append(str(expanded))
    return paths


def _reject_legacy_sandbox(document: Any) -> None:
    conflicts = [
        key for key in ("sandbox_mode", "sandbox_workspace_write") if key in document
    ]
    if conflicts:
        raise ValueError(
            "Codex permission profiles cannot be combined with legacy settings: "
            + ", ".join(conflicts)
        )


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o600
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", text=True
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w") as stream:
            stream.write(content)
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()
